Repository kubesphere-extensions/ks-extensions, pull requests merged in 2024-10, with the labels that each got.

#32 Fix chart requires kubeVersion: >=1.19.0 which is incompatible with Kubernetes v1.31.1-eks-ce1d5eb
  loki/extension.yaml
  network/extension.yaml
Labels: release-note, lgtm, approved, size/XS

#33 fix typos
  whizard-monitoring/README.md
  whizard-monitoring/README_zh.md
Labels: lgtm, approved, release-note-none, size/XS

#34 fix typos
  whizard-monitoring/README.md
  whizard-monitoring/README_zh.md
Labels: lgtm, approved, release-note-none, size/XS

#31 添加kubeedge扩展插件
  kubeedge/CHANGELOG.md
  kubeedge/CHANGELOG_zh.md
  kubeedge/README.md
  kubeedge/README_zh.md
  kubeedge/charts/cloudcore/Chart.yaml
  kubeedge/charts/cloudcore/README.md
  kubeedge/charts/cloudcore/crds/apps_v1alpha1_edgeapplication.yaml
  kubeedge/charts/cloudcore/crds/apps_v1alpha1_nodegroup.yaml
  kubeedge/charts/cloudcore/crds/cluster_objectsync_v1alpha1.yaml
  kubeedge/charts/cloudcore/crds/devices_v1alpha2_device.yaml
  kubeedge/charts/cloudcore/crds/devices_v1alpha2_devicemodel.yaml
  kubeedge/charts/cloudcore/crds/objectsync_v1alpha1.yaml
  kubeedge/charts/cloudcore/crds/operations_v1alpha1_nodeupgradejob.yaml
  kubeedge/charts/cloudcore/crds/router_v1_rule.yaml
  kubeedge/charts/cloudcore/crds/router_v1_ruleEndpoint.yaml
  kubeedge/charts/cloudcore/templates/_helpers.tpl
  kubeedge/charts/cloudcore/templates/_images.tpl
  kubeedge/charts/cloudcore/templates/apiservices.yaml
  kubeedge/charts/cloudcore/templates/configmap_cloudcore.yaml
  kubeedge/charts/cloudcore/templates/daemonset_iptablesmanager.yaml
  kubeedge/charts/cloudcore/templates/deployment_cloudcore.yaml
  kubeedge/charts/cloudcore/templates/deployment_controllermanager.yaml
  kubeedge/charts/cloudcore/templates/deployment_kubeedgeproxy.yaml
  kubeedge/charts/cloudcore/templates/namespace.yaml
  kubeedge/charts/cloudcore/templates/rbac-edgeservice.yaml
  kubeedge/charts/cloudcore/templates/rbac_cloudcore.yaml
  kubeedge/charts/cloudcore/templates/rbac_controllermanager.yaml
  kubeedge/charts/cloudcore/templates/rbac_iptablesmanager.yaml
  kubeedge/charts/cloudcore/templates/secret_cloudcore.yaml
  kubeedge/charts/cloudcore/templates/service_cloudcore.yaml
  kubeedge/charts/cloudcore/templates/service_kubeedgeproxy.yaml
  kubeedge/charts/cloudcore/values.yaml
  kubeedge/charts/frontend/Chart.yaml
  kubeedge/charts/frontend/templates/NOTES.txt
  kubeedge/charts/frontend/templates/configmap.yaml
  kubeedge/charts/frontend/templates/extensions.yaml
  kubeedge/charts/frontend/templates/helps.tpl
  kubeedge/charts/frontend/values.yaml
  kubeedge/extension.yaml
  kubeedge/favicon.svg
  kubeedge/permissions.yaml
  kubeedge/values.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, size/XXL

#35 Unified Images format
  kubefed/extension.yaml
  storage-utils/extension.yaml
  tower/extension.yaml
  whizard-alerting/extension.yaml
  whizard-monitoring/extension.yaml
Labels: do-not-merge/release-note-label-needed, lgtm, approved, size/M

#36 Update incorrect images for extensions
  gatekeeper/values.yaml
  loki/extension.yaml
  opensearch/extension.yaml
  opensearch/values.yaml
Labels: lgtm, approved, release-note-none, size/S
