Repository kubesphere-extensions/ks-extensions, pull requests merged in 2024-09, with the labels that each got.

#7 feat: add museum image.
  .github/workflows/build-extensions-museum.yaml
  .gitignore
  Dockerfile
  Makefile
Labels: size/L, release-note, lgtm, approve, approved

#8 feat: add museum image.
  .github/workflows/build-extensions-museum.yaml
Labels: lgtm, approved, release-note-none, size/XS

#9 feat: change image name to ks-extensions-museum
  .github/workflows/build-extensions-museum.yaml
  Dockerfile
  Makefile
Labels: lgtm, release-note-none, size/S

#10 [whizard-monitoring] add whizard-monitoring extension
  whizard-monitoring/.helmignore
  whizard-monitoring/CHANGELOG.md
  whizard-monitoring/CHANGELOG_zh.md
  whizard-monitoring/LICENSE
  whizard-monitoring/README.md
  whizard-monitoring/README_zh.md
  whizard-monitoring/charts/dcgm-exporter-3.4.0.tgz
  whizard-monitoring/charts/kube-prometheus-stack-61.3.6.tgz
  whizard-monitoring/charts/whizard-monitoring-helper/.helmignore
  whizard-monitoring/charts/whizard-monitoring-helper/Chart.yaml
  whizard-monitoring/charts/whizard-monitoring-helper/README.md
  whizard-monitoring/charts/whizard-monitoring-helper/crds/monitoring-clusterdashboard-customResourceDefinition.yaml
  whizard-monitoring/charts/whizard-monitoring-helper/crds/monitoring-dashboard-customResourceDefinition.yaml
  whizard-monitoring/charts/whizard-monitoring-helper/templates/_helpers.tpl
  whizard-monitoring/charts/whizard-monitoring-helper/templates/extra-objects.yaml
  whizard-monitoring/charts/whizard-monitoring-helper/templates/hook.yaml
  whizard-monitoring/charts/whizard-monitoring-helper/templates/reverseproxy.yaml
  whizard-monitoring/charts/whizard-monitoring-helper/templates/roletemplate.yaml
  whizard-monitoring/charts/whizard-monitoring-helper/values.yaml
  whizard-monitoring/extension.yaml
  whizard-monitoring/permissions.yaml
  whizard-monitoring/static/favicon.svg
  whizard-monitoring/values.yaml
  whizard-telemetry/README.md
  whizard-telemetry/README_zh.md
  whizard-telemetry/values.yaml
Labels: release-note, size/XXL

#12 [whizard-monitoring] add frontend subchart
  whizard-monitoring/charts/frontend/Chart.yaml
  whizard-monitoring/charts/frontend/templates/NOTES.txt
  whizard-monitoring/charts/frontend/templates/configmap.yaml
  whizard-monitoring/charts/frontend/templates/extensions.yaml
  whizard-monitoring/charts/frontend/templates/helps.tpl
  whizard-monitoring/charts/frontend/values.yaml
  whizard-monitoring/extension.yaml
Labels: size/L, lgtm, release-note-none

#13 Add OWNERS
  OWNERS
Labels: release-note-none, size/S

#14 add license for storage-utils
  storage-utils/LICENSE
Labels: size/L, release-note, lgtm, approved

#15 feat: update gatekeeper license to Apache 2.0
  gatekeeper/LICENSE
Labels: size/L, lgtm, approved, release-note-none

#18 add loki extension
  loki/.helmignore
  loki/CHANGELOG.md
  loki/CHANGELOG_zh.md
  loki/LICENSE
  loki/README.md
  loki/README_zh.md
  loki/charts/loki-6.6.2.tgz
  loki/extension.yaml
  loki/permissions.yaml
  loki/static/loki.png
  loki/values.yaml
  opensearch/values.yaml
Labels: lgtm, approved, release-note-none, size/XL

#17 [gateway] add extension gateway
  gateway/.helmignore
  gateway/CHANGELOG.md
  gateway/CHANGELOG_zh.md
  gateway/README.md
  gateway/README_zh.md
  gateway/charts/backend/Chart.yaml
  gateway/charts/backend/crds/gateway.kubesphere.io_gateways.yaml
  gateway/charts/backend/files/upgrade-cluster-gateway.sh
  gateway/charts/backend/templates/NOTES.txt
  gateway/charts/backend/templates/apiserver-deployment.yaml
  gateway/charts/backend/templates/apiserver-service.yaml
  gateway/charts/backend/templates/controller-manager-deployment.yaml
  gateway/charts/backend/templates/controller-manager-service.yaml
  gateway/charts/backend/templates/extensions.yaml
  gateway/charts/backend/templates/gateway-config-configmap.yaml
  gateway/charts/backend/templates/gateway-upgrader-config.yaml
  gateway/charts/backend/templates/gateway-upgrader-job.yaml
  gateway/charts/backend/templates/helps.tpl
  gateway/charts/backend/templates/iam_authenticated.yaml
  gateway/charts/backend/templates/iam_categories.yaml
  gateway/charts/backend/templates/iam_roletemplates.yaml
  gateway/charts/backend/templates/images.tpl
  gateway/charts/backend/templates/nginx-ingress-configmap-4.3.0.yaml
  gateway/charts/backend/templates/prometheus-ingress-rules.yaml
  gateway/charts/backend/templates/serviceaccount.yaml
  gateway/charts/backend/values.yaml
  gateway/charts/frontend/Chart.yaml
  gateway/charts/frontend/templates/NOTES.txt
  gateway/charts/frontend/templates/configmap.yaml
  gateway/charts/frontend/templates/extensions.yaml
  gateway/charts/frontend/templates/helps.tpl
  gateway/charts/frontend/values.yaml
  gateway/extension.yaml
  gateway/permissions.yaml
  gateway/static/favicon.svg
  gateway/values.yaml
Labels: release-note, lgtm, approved, size/XXL

#21 add whizard-alerting extension
  whizard-alerting/.helmignore
  whizard-alerting/CHANGELOG.md
  whizard-alerting/CHANGELOG_zh.md
  whizard-alerting/LICENSE
  whizard-alerting/README.md
  whizard-alerting/README_zh.md
  whizard-alerting/charts/agent-0.1.17.tgz
  whizard-alerting/charts/extension-0.1.23.tgz
  whizard-alerting/charts/frontend/Chart.yaml
  whizard-alerting/charts/frontend/templates/NOTES.txt
  whizard-alerting/charts/frontend/templates/configmap.yaml
  whizard-alerting/charts/frontend/templates/extensions.yaml
  whizard-alerting/charts/frontend/templates/helps.tpl
  whizard-alerting/charts/frontend/values.yaml
  whizard-alerting/extension.yaml
  whizard-alerting/favicon.svg
  whizard-alerting/permissions.yaml
  whizard-alerting/swagger.yaml
  whizard-alerting/values.yaml
Labels: lgtm, approved, release-note-none, size/XXL

#23 add network extension
  network/CHANGELOG.md
  network/CHANGELOG_zh.md
  network/LICENSE
  network/README.md
  network/README_zh.md
  network/api_doc.md
  network/charts/frontend/Chart.yaml
  network/charts/frontend/templates/NOTES.txt
  network/charts/frontend/templates/configmap.yaml
  network/charts/frontend/templates/extensions.yaml
  network/charts/frontend/templates/helps.tpl
  network/charts/frontend/values.yaml
  network/charts/network/Chart.yaml
  network/charts/network/crds/network.kubesphere.io_namespacenetworkpolicies.yaml
  network/charts/network/templates/NOTES.txt
  network/charts/network/templates/apiserver-deployment.yaml
  network/charts/network/templates/apiserver-service.yaml
  network/charts/network/templates/controller-deployment.yaml
  network/charts/network/templates/controller-service.yaml
  network/charts/network/templates/extensions.yaml
  network/charts/network/templates/helps.tpl
  network/charts/network/templates/images.tpl
  network/charts/network/templates/rbac-apiserver.yaml
  network/charts/network/templates/rbac-controller.yaml
  network/charts/network/templates/roletemplate.yaml
  network/charts/network/templates/serviceaccount.yaml
  network/charts/network/templates/webhook.yaml
  network/charts/network/values.yaml
  network/extension.yaml
  network/permissions.yaml
  network/static/favicon.svg
  network/swagger.yaml
  network/values.yaml
Labels: release-note, lgtm, approved, size/XXL

#25 [grafana] add LICENSE
  grafana/LICENSE
Labels: lgtm, approved, release-note-none, size/XL

#27 Add member to owner
  OWNERS
Labels: approved, release-note-none, size/XS

#26 update whizard-monitoring frontend chart
  whizard-monitoring/charts/frontend/values.yaml
Labels: release-note, lgtm, approved, size/XS

#28 update whizard-monitoring version
  whizard-monitoring/extension.yaml
Labels: release-note, lgtm, approved, size/XS

#29 update whizard-monitoring frontend version and appVersion
  whizard-monitoring/charts/frontend/Chart.yaml
Labels: release-note, lgtm, approved, size/XS

#30 servicemesh: label istio-system for ks
  servicemesh/charts/backend/templates/istio-pre-install-job.yaml
Labels: lgtm, approved, release-note-none, size/XS
