Repository kubesphere-extensions/ks-extensions, pull requests merged in 2025-06, with the labels that each got.

#71 update ob-operator
  ob-operator/charts/ob-operator-2.3.1.tgz
  ob-operator/extension.yaml
  ob-operator/values.yaml
Labels: approved, release-note-none, size/M

#72 update oceanbase-dashboard
  oceanbase-dashboard/charts/entrypoint/Chart.yaml
  oceanbase-dashboard/charts/entrypoint/templates/iframe.yaml
  oceanbase-dashboard/charts/entrypoint/templates/ingress.yaml
  oceanbase-dashboard/charts/entrypoint/templates/jsbundle.yaml
  oceanbase-dashboard/charts/entrypoint/templates/link.yaml
  oceanbase-dashboard/charts/entrypoint/values.yaml
  oceanbase-dashboard/charts/oceanbase-dashboard-0.4.0.tgz
  oceanbase-dashboard/extension.yaml
  oceanbase-dashboard/values.yaml
Labels: approved, release-note-none, size/XL

#74 update ob-operator to version 2.3.2
  ob-operator/CHANGELOG.md
  ob-operator/CHANGELOG_zh.md
  ob-operator/charts/ob-operator-2.3.2.tgz
  ob-operator/extension.yaml
  ob-operator/values.yaml
Labels: kind/feature, lgtm, approved, size/S
