Repository kubesphere-extensions/ks-extensions, pull requests merged in 2025-04, with the labels that each got.

#53 update devops
  devops/CHANGELOG.md
  devops/CHANGELOG_zh.md
  devops/README.md
  devops/README_zh.md
  devops/charts/agent/Chart.yaml
  devops/charts/agent/charts/jenkins/templates/_helpers.tpl
  devops/charts/agent/charts/jenkins/templates/config.yaml
  devops/charts/agent/charts/jenkins/templates/jenkins-casc-config.yml
  devops/charts/agent/charts/jenkins/templates/jenkins-oauth-client.yaml
  devops/charts/agent/charts/jenkins/values.yaml
  devops/charts/agent/templates/cluster-step-templates.yaml
  devops/charts/agent/templates/cluster-template-golang.yaml
  devops/charts/agent/templates/cluster-template-maven.yaml
  devops/charts/agent/templates/cluster-template-nodejs.yaml
  devops/charts/agent/templates/cronjob-gc.yaml
  devops/charts/agent/templates/deployment-apiserver.yaml
  devops/charts/agent/templates/iam-roletemplates.yaml
  devops/charts/agent/values.yaml
  devops/charts/extension/Chart.yaml
  devops/charts/extension/templates/_helpers.tpl
  devops/charts/extension/templates/deployment-apiserver.yaml
  devops/charts/extension/templates/iam-globalrole.yaml
  devops/charts/extension/templates/iam-roletemplates.yaml
  devops/charts/extension/templates/secret.yaml
  devops/charts/extension/values.yaml
  devops/extension.yaml
  devops/values.yaml
Labels: release-note, lgtm, approved, size/XL, kind/bug

#55 login to docker
  .github/workflows/extensions-precheck.yaml
Labels: release-note-none, size/XS

#56 Update gateway version to v1.0.4
  gateway/CHANGELOG.md
  gateway/CHANGELOG_zh.md
  gateway/README.md
  gateway/README_zh.md
  gateway/charts/backend-0.2.0.tgz
  gateway/charts/frontend-0.1.2.tgz
  gateway/extension.yaml
  gateway/values.yaml
Labels: size/L, release-note, lgtm, approved

#58 update gateway version to v1.0.5
  gateway/.helmignore
  gateway/CHANGELOG.md
  gateway/CHANGELOG_zh.md
  gateway/README_zh.md
  gateway/charts/backend-0.2.0.tgz
  gateway/charts/backend/Chart.yaml
  gateway/charts/backend/crds/gateway.kubesphere.io_gateways.yaml
  gateway/charts/backend/files/upgrade-cluster-gateway.sh
  gateway/charts/backend/templates/NOTES.txt
  gateway/charts/backend/templates/apiserver-deployment.yaml
  gateway/charts/backend/templates/apiserver-service.yaml
  gateway/charts/backend/templates/controller-manager-deployment.yaml
  gateway/charts/backend/templates/controller-manager-service.yaml
  gateway/charts/backend/templates/extensions.yaml
  gateway/charts/backend/templates/gateway-config-configmap.yaml
  gateway/charts/backend/templates/gateway-upgrader-config.yaml
  gateway/charts/backend/templates/gateway-upgrader-job.yaml
  gateway/charts/backend/templates/helps.tpl
  gateway/charts/backend/templates/iam_authenticated.yaml
  gateway/charts/backend/templates/iam_categories.yaml
  gateway/charts/backend/templates/iam_roletemplates.yaml
  gateway/charts/backend/templates/images.tpl
  gateway/charts/backend/templates/nginx-ingress-configmap-4.3.0.yaml
  gateway/charts/backend/templates/prometheus-ingress-rules.yaml
  gateway/charts/backend/templates/serviceaccount.yaml
  gateway/charts/backend/values.yaml
  gateway/charts/frontend-0.1.2.tgz
  gateway/charts/frontend/Chart.yaml
  gateway/charts/frontend/templates/NOTES.txt
  gateway/charts/frontend/templates/configmap.yaml
  gateway/charts/frontend/templates/extensions.yaml
  gateway/charts/frontend/templates/helps.tpl
  gateway/charts/frontend/values.yaml
  gateway/extension.yaml
Labels: size/XXL

#62 Update openpitrix version to 2.0.2
  openpitrix/.helmignore
  openpitrix/CHANGELOG.md
  openpitrix/CHANGELOG_zh.md
  openpitrix/charts/apps-0.1.0.tgz
  openpitrix/charts/apps/Chart.yaml
  openpitrix/charts/apps/templates/NOTES.txt
  openpitrix/charts/apps/templates/deployment.yaml
  openpitrix/charts/apps/templates/extensions.yaml
  openpitrix/charts/apps/templates/helps.tpl
  openpitrix/charts/apps/templates/service.yaml
  openpitrix/charts/apps/templates/tests/test-connection.yaml
  openpitrix/charts/apps/values.yaml
  openpitrix/extension.yaml
  openpitrix/values.yaml
Labels: size/L, release-note, lgtm, approved

#63 Update gateway to 1.0.5
  gateway/.helmignore
  gateway/CHANGELOG.md
  gateway/CHANGELOG_zh.md
  gateway/README_zh.md
  gateway/charts/backend-0.2.0.tgz
  gateway/charts/backend/Chart.yaml
  gateway/charts/backend/crds/gateway.kubesphere.io_gateways.yaml
  gateway/charts/backend/files/upgrade-cluster-gateway.sh
  gateway/charts/backend/templates/NOTES.txt
  gateway/charts/backend/templates/apiserver-deployment.yaml
  gateway/charts/backend/templates/apiserver-service.yaml
  gateway/charts/backend/templates/controller-manager-deployment.yaml
  gateway/charts/backend/templates/controller-manager-service.yaml
  gateway/charts/backend/templates/extensions.yaml
  gateway/charts/backend/templates/gateway-config-configmap.yaml
  gateway/charts/backend/templates/gateway-upgrader-config.yaml
  gateway/charts/backend/templates/gateway-upgrader-job.yaml
  gateway/charts/backend/templates/helps.tpl
  gateway/charts/backend/templates/iam_authenticated.yaml
  gateway/charts/backend/templates/iam_categories.yaml
  gateway/charts/backend/templates/iam_roletemplates.yaml
  gateway/charts/backend/templates/images.tpl
  gateway/charts/backend/templates/nginx-ingress-configmap-4.3.0.yaml
  gateway/charts/backend/templates/prometheus-ingress-rules.yaml
  gateway/charts/backend/templates/serviceaccount.yaml
  gateway/charts/backend/values.yaml
  gateway/charts/frontend-0.1.2.tgz
  gateway/charts/frontend/Chart.yaml
  gateway/charts/frontend/templates/NOTES.txt
  gateway/charts/frontend/templates/configmap.yaml
  gateway/charts/frontend/templates/extensions.yaml
  gateway/charts/frontend/templates/helps.tpl
  gateway/charts/frontend/values.yaml
  gateway/extension.yaml
  gateway/static/static/favicon.svg
Labels: release-note, lgtm, approved, size/XXL

#67 update gateway version to v1.0.5
  gateway/charts/backend-0.2.0.tgz
  gateway/charts/frontend-0.1.2.tgz
Labels: lgtm, approved, size/XS
