Repository kubesphere-extensions/ks-extensions, pull requests merged in 2025-02, with the labels that each got.

#41 [nvidia-gpu-operator] add NVIDIA GPU Operator extension
  nvidia-gpu-operator/CHANGELOG.md
  nvidia-gpu-operator/CHANGELOG_zh.md
  nvidia-gpu-operator/README.md
  nvidia-gpu-operator/README_zh.md
  nvidia-gpu-operator/charts/gpu-operator-v23.9.2.tgz
  nvidia-gpu-operator/extension.yaml
  nvidia-gpu-operator/permissions.yaml
  nvidia-gpu-operator/static/GPUoperator.png
  nvidia-gpu-operator/static/nvidia-gpu-operator-image.jpg
  nvidia-gpu-operator/values.yaml
Labels: release-note, lgtm, approved, size/XXL

#40 feat: add deepseek extension
  deepseek/README.md
  deepseek/README_zh.md
  deepseek/charts/backend/Chart.yaml
  deepseek/charts/backend/templates/_helper.tpl
  deepseek/charts/backend/templates/_image.tpl
  deepseek/charts/backend/templates/_resources.tpl
  deepseek/charts/backend/templates/autoscaler.yaml
  deepseek/charts/backend/templates/chat.yaml
  deepseek/charts/backend/templates/ingress.yaml
  deepseek/charts/backend/templates/pvc.yaml
  deepseek/charts/backend/templates/server.yaml
  deepseek/charts/backend/values.yaml
  deepseek/charts/frontend/Chart.yaml
  deepseek/charts/frontend/templates/configmap.yaml
  deepseek/charts/frontend/templates/extensions.yaml
  deepseek/charts/frontend/templates/helps.tpl
  deepseek/charts/frontend/values.yaml
  deepseek/extension.yaml
  deepseek/permissions.yaml
  deepseek/static/favicon.png
  deepseek/values.yaml
Labels: release-note, lgtm, approved, size/XXL

#43 fix: Adjust the value structure
  deepseek/README.md
  deepseek/README_zh.md
  deepseek/charts/backend/templates/ingress.yaml
  deepseek/charts/backend/values.yaml
  deepseek/charts/frontend/templates/configmap.yaml
  deepseek/charts/frontend/templates/extensions.yaml
  deepseek/charts/frontend/values.yaml
  deepseek/values.yaml
Labels: lgtm, approved, release-note-none, size/XL

#44 fix: fix readme
  deepseek/README.md
  deepseek/README_zh.md
Labels: lgtm, approved, release-note-none, size/S
