Repository kubesphere-extensions/ks-extensions, pull requests merged in 2025-03, with the labels that each got.

#45 [metrics-server] update extension
  metrics-server/CHANGELOG.md
  metrics-server/CHANGELOG_zh.md
  metrics-server/extension.yaml
  metrics-server/values.yaml
Labels: release-note, lgtm, approved, size/S

#49 feat: refact dockerfile
  .extensions-museum/deepseek-0.1.0.tgz
  .extensions-museum/devops-1.1.1.tgz
  .extensions-museum/gatekeeper-1.0.1.tgz
  .extensions-museum/gateway-1.0.2.tgz
  .extensions-museum/grafana-10.4.1.tgz
  .extensions-museum/kubeedge-1.13.1.tgz
  .extensions-museum/kubefed-1.0.0.tgz
  .extensions-museum/loki-1.0.1.tgz
  .extensions-museum/metrics-server-0.7.0.tgz
  .extensions-museum/metrics-server-0.7.1.tgz
  .extensions-museum/network-1.1.0.tgz
  .extensions-museum/nvidia-gpu-operator-23.9.2.tgz
  .extensions-museum/openpitrix-2.0.1.tgz
  .extensions-museum/opensearch-2.11.1.tgz
  .extensions-museum/servicemesh-1.0.0.tgz
  .extensions-museum/storage-utils-1.0.0.tgz
  .extensions-museum/tower-1.0.0.tgz
  .extensions-museum/vector-1.0.4.tgz
  .extensions-museum/whizard-alerting-1.0.3.tgz
  .extensions-museum/whizard-events-1.2.0.tgz
  .extensions-museum/whizard-logging-1.2.2.tgz
  .extensions-museum/whizard-monitoring-1.1.0.tgz
  .extensions-museum/whizard-monitoring-1.1.1.tgz
  .extensions-museum/whizard-notification-2.5.9.tgz
  .extensions-museum/whizard-telemetry-1.2.2.tgz
  Dockerfile
Labels: kind/feature, release-note, lgtm, approved, size/S

#50 only support manual trigger to build latest image
  .github/workflows/build-extensions-museum.yaml
Labels: kind/feature, release-note-none, size/XS

#52 Add more branches to support different KubeSphere versions.
  .github/workflows/build-extensions-charts.yaml
Labels: kind/feature, release-note-none, size/XS
